### PR TITLE
Fix maxUnavailable to round down instead up

### LINKED ISSUE #1075: kube-state-metrics should round down maxUnavailable
/kind bug

For a Deployment with `spec.strategy.rollingUpdate.maxUnavailable` specified as a percentage, kube-state-metrics rounds _up_ to the nearest pod, while Kubernetes rounds _down_ to the nearest pod.

https://github.com/kubernetes/kubernetes/blob/479759ed163bd232ba92351340e2b84de26a1b99/pkg/controller/deployment/util/deployment_util.go#L888

The rounding logic in kube-state-metrics should match the rounding logic used by Kubernetes deployment code.

### PR DESCRIPTION
**Pull request by gregory-lyons**
**What this PR does / why we need it**:
kube-state-metrics rounding logic should match Kubernetes rounding logic

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1075

### CODE REVIEW

File: internal/store/deployment_test.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ var (
 	depl2Replicas int32 = 5
 
 	depl1MaxUnavailable = intstr.FromInt(10)
-	depl2MaxUnavailable = intstr.FromString("20%")
+	depl2MaxUnavailable = intstr.FromString("25%")
```
Comment (gregory-lyons) [inline internal/store/deployment_test.go]: With rounding up, this will fail to produce the existing expected value of 1. With my change (rounding down) we still produce the existing expected value.

**Comment by tariq1890** [comment]
Thanks for fixing this @gregory-lyons. Can you point this to the `release-1.9` branch?

**Comment by tariq1890** [comment]
@lilic @brancz I think we should get a patch release out of this. Thoughts?

**Comment by gregory-lyons** [comment]
@tariq1890 do you want me to rebase onto the top of release-1.9 branch?

**Comment by tariq1890** [comment]
Yes please.

**Comment by lilic** [comment]
> @lilic @brancz I think we should get a patch release out of this. Thoughts?

@tariq1890 was this "bug" introduced in the 1.9 branch? 🤔

**Comment by tariq1890** [comment]
@LiliC fair point :). In that case, we could just retarget to master.

**Comment by tariq1890** [comment]
@gregory-lyons sorry for the inconvenience; can we retarget this back to the master branch.

**Comment by gregory-lyons** [comment]
@tariq1890 no worries, updated it

**Comment by brancz** [comment]
The kube bot requires us to not have the "Fixes #..." type thing in the commit message. Can you remove that? Then we can merge this.

**Comment by tariq1890** [comment]
Thanks @gregory-lyons :)!
