### PR TITLE
fix: de-duplication of custom resource metrics

### LINKED ISSUE #2446: Duplicate samples for customResourceState metrics
**What happened**:

We upgraded to Prometheus 2.52 and started receiving the following warnings:
```
ts=2024-07-11T06:43:56.289Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=serviceMonitor/k8s-monitoring/kube-prometheus-stack-kube-state-metrics/0 target=http://x.x.x.x:8080/metrics msg="Error on inge
sting samples with different value but same timestamp" num_dropped=23
```

We found similar open issues about duplicates, but this one is about all the metrics configured via customResourceState config.

After a fresh restart of the kube-state-metrics pod, the metrics are not duplicated. However after a while, each of the metrics, configured via customResourceState is suddenly present twice or even multiple times:

```
# There is exactly 1 kind: HelmRepository
$ kubectl get helmrepositories.source.toolkit.fluxcd.io -n flux-system
NAME     URL                     AGE
acraks   oci://xxxx.azurecr.io   8d

# After kube-state-metrics runs a while, it returns 3 exact same metrics
$ curl http://kube-prometheus-stack-kube-state-metrics.k8s-monitoring:8080/metrics | grep HelmRepository | grep flux-system
gotk_resource_info{customresource_group="source.toolkit.fluxcd.io",customresource_kind="HelmRepository",customresource_version="v1",exported_namespace="flux-system",name="acraks",url="oci://xxxx.azurecr.io"} 1
gotk_resource_info{customresource_group="source.toolkit.fluxcd.io",customresource_kind="HelmRepository",customresource_version="v1",exported_namespace="flux-system",name="acraks",url="oci://xxxx.azurecr.io"} 1
gotk_resource_info{customresource_group="source.toolkit.fluxcd.io",customresource_kind="HelmRepository",customresource_version="v1",exported_namespace="flux-system",name="acraks",url="oci://xxxx.azurecr.io"} 1

# After a restart of kube-state-metrics, there are no duplications for a while
$ kubectl delete pod kube-prometheus-stack-kube-state-metrics-76968f786b-z7m8t
$ curl http://kube-prometheus-stack-kube-state-metrics.k8s-monitoring:8080/metrics | grep HelmRepository | grep flux-system
gotk_resource_info{customresource_group="source.toolkit.fluxcd.io",customresource_kind="HelmRepository",customresource_version="v1",exported_namespace="flux-system",name="acraks",url="oci://xxxx.azurecr.io"} 1
```

**What you expected to happen**:

No duplicates, as the resource exists just once and all labels are the same.

**How to reproduce it (as minimally and precisely as possible)**:

Use the configuration provided here: https://fluxcd.io/flux/monitoring/custom-metrics or the customResourceState config below:

```
apiVersion: v1
data:
  config.yaml: |
    spec:
      resources:
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: HelmRepository
          version: v1
        metricNamePrefix: gotk
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux HelmRepository resource.
          labelsFromPath:
            exported_namespace:
            - metadata
            - namespace
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
            url:
            - spec
            - url
          name: resource_info
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.12.0
    helm.sh/chart: kube-state-metrics-5.20.0
    helm.toolkit.fluxcd.io/name: kube-prometheus-stack
    helm.toolkit.fluxcd.io/namespace: flux-system
    release: kube-prometheus-stack
  name: kube-prometheus-stack-kube-state-metrics-customresourcestate-config
  namespace: k8s-monitoring
```

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version: 2.12.0
* Kubernetes version (use `kubectl version`): 1.29.4
* Cloud provider or hardware configuration: AKS

### PR DESCRIPTION
**Pull request by bartlettc22**
**What this PR does / why we need it**:
Fixes an issue that causes custom resource metrics to duplicate every time a CR resource that KSM is watching changed.  The duplication was happening because the informer events (add/delete) triggered a subsequent call to `WithEnabledResources` in `store.Builder`.  This would append, but not de-duplicate the CR resources to the `enabledResources` list. This, in turn, would cause the custom resources to be be added multiple times when the store was built.

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
Does not change cardinality

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2446

### CODE REVIEW

**Review by rexagod — CHANGES_REQUESTED** [review]
Requested a minor change below. Thank you for the much needed patch!

**Comment by bartlettc22** [comment]
> Requested a minor change below. Thank you for the much needed patch!

Updated - thanks for the suggestion!

**Comment by mrueg** [comment]
/lgtm

/hold 
for others to review

File: internal/store/builder_test.go [hunk 1]
```diff
@@ -196,3 +197,64 @@ func TestWithAllowAnnotations(t *testing.T) {
...
+	}
+	for _, test := range tests {
+		b := NewBuilder()
+
+		// Set the enabled resources.
+		err := b.WithEnabledResources(test.EnabledResources)
+		if test.err.expectedResourceError {
+			if err == nil {
+				t.Log("Did not expect error while setting resources (--resources).")
+				t.Fatal("Test error for Desc: %s. Got Error: %v", test.Desc, err)
```
Comment (mrueg) [inline internal/store/builder_test.go:244]:
```suggestion
				t.Fatalf("Test error for Desc: %s. Got Error: %v", test.Desc, err)
```
