### PR TITLE
Handle unit length `valueFrom` values

### LINKED ISSUE #1947: Dissimilar erroring behaviours between Gauge and other types
**What happened**: Defined the below configuration for the KSM CRS config.

<details>
<summary>Details</summary>

```yaml
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "route.openshift.io"
        version: "v1"
        kind: "Route"
      metrics:
        - name: "openshift_route_created"
          help: "Unix creation timestamp"
          each:
            type: Gauge
            gauge:
              path: [metadata]
              labelsFromPath:
                route: [name]
                namespace: [namespace]
              valueFrom: [creationTimestamp] # not applicable in case of info type, since this will always be 1 in that case
```

</details>

**What you expected to happen**: Metrics are generated based on the aforementioned config. Instead, this errored out. However, on changing the type to `Info`, it works. Gauge should typically check in such cases if the string could be typecasted into a numeric value, and use that.

<details>
<summary>Details</summary>

```console
I0109 13:29:12.073930   14958 wrapper.go:78] Starting kube-state-metrics
I0109 13:29:12.074110   14958 server.go:173] "Used CRD resources only" resources=[routes]
I0109 13:29:12.074133   14958 types.go:184] "Using all namespaces"
I0109 13:29:12.074147   14958 server.go:203] "Metric allow-denylisting" allowDenyStatus="Excluding the following lists that were on denylist: "
I0109 13:29:12.076082   14958 server.go:348] "Tested communication with server"
I0109 13:29:13.166123   14958 server.go:353] "Run with Kubernetes cluster version" major="1" minor="25" gitVersion="v1.25.2+761cfe9" gitTreeState="clean" gitCommit="e313ec204d698755f1772515a87764bf524c8ac6" platform="linux/amd64"
I0109 13:29:13.166441   14958 server.go:354] "Communication with server successful"
I0109 13:29:13.168781   14958 server.go:300] "Started metrics server" metricsServerAddress="[::]:8080"
I0109 13:29:13.172008   14958 server.go:71] levelinfomsgListening onaddress[::]:8080
I0109 13:29:13.169082   14958 metrics_handler.go:97] "Autosharding disabled"
I0109 13:29:13.169994   14958 server.go:289] "Started kube-state-metrics self metrics server" telemetryAddress="[::]:8081"
I0109 13:29:13.172816   14958 server.go:71] levelinfomsgListening onaddress[::]:8081
I0109 13:29:13.172936   14958 server.go:71] levelinfomsgTLS is disabled.http2falseaddress[::]:8081
I0109 13:29:13.173042   14958 server.go:71] levelinfomsgTLS is disabled.http2falseaddress[::]:8080
I0109 13:29:13.173233   14958 custom_resource_metrics.go:79] "Custom resource state added metrics" familyNames=[kube_crd_openshift_route_created kube_crd_openshift_route_info kube_crd_openshift_route_status kube_crd_openshift_route_labels]
I0109 13:29:13.173343   14958 builder.go:254] "Active resources" activeStoreNames="routes"
E0109 13:29:15.649784   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [namespace]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649842   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [uid]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649868   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [resourceVersion]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649894   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [creationTimestamp]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649919   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [labels]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649944   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [annotations]: [creationTimestamp]: expected number but found nil value"
E0109 13:29:15.649972   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [managedFields]: [creationTimestamp]: expected number but was invalid list index: creationTimestamp"
E0109 13:29:15.649998   14958 registry_factory.go:596] "kube_crd_openshift_route_created" err="[metadata]: [name]: [creationTimestamp]: expected number but found nil value"
```

</details>

**How to reproduce it (as minimally and precisely as possible)**: Use the config above and run KSM: `kube-state-metrics --kubeconfig=$KUBECONFIG --custom-resource-state-config-file=[config] --custom-resource-state-only`.

**Anything else we need to know?**: I've also pasted the object schema below.

<details>
<summary>Details</summary>

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: "2023-01-09T07:01:31Z"
  labels:
    app: ...
  name: ...
  namespace: ...
  resourceVersion: "18329"
  uid: 6cc62136-fa92-4e14-af85-74e356c6c3ac
spec:
  host: ...
  port:
    targetPort: ...
  tls:
    insecureEdgeTerminationPolicy: ...
    termination: ...
  to:
    kind: Service
    name: ...
    weight: 100
  wildcardPolicy: ...
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2023-01-09T07:01:31Z"
      status: "True"
      type: ...
    host: ...
    routerCanonicalHostname: ...
    routerName: ...
    wildcardPolicy: ...
```

</details>

**Environment**:
- kube-state-metrics version: HEAD
- Kubernetes version (use `kubectl version`).

<details>
<summary>Details</summary>

```console
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"archive", BuildDate:"2022-11-11T00:00:00Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2+761cfe9", GitCommit:"e313ec204d698755f1772515a87764bf524c8ac6", GitTreeState:"clean", BuildDate:"2022-11-17T06:55:08Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### PR DESCRIPTION
**Pull request by rexagod**
**What this PR does / why we need it**: Handle unit length `valueFrom` values and skip strings where we expect them to be type-cast-able to `float64`, instead of erroring, since that is the expected behavior, and what's being done for other types.

**How does this change affect the cardinality of KSM**: No change.

**Which issue(s) this PR fixes**: Fixes #1947

### CODE REVIEW

File: pkg/customresourcestate/registry_factory.go [hunk 1]
```diff
@@ -217,7 +217,35 @@ func (c *compiledGauge) Values(v interface{}) (result []eachValue, errs []error)
 	switch iter := v.(type) {
 	case map[string]interface{}:
 		for key, it := range iter {
-			ev, err := c.value(it)
+			// Try to deduce `valueFrom`'s value from the current element.
+			var ev *eachValue
+			var err error
+			var didResolveValueFrom bool
+			sValueFrom := c.ValueFrom.String()
+			if !strings.Contains(sValueFrom, ",") &&
```
Comment (mrueg) [inline pkg/customresourcestate/registry_factory.go:225]: can you explain in a comment what this and the following lines are doing?

File: pkg/customresourcestate/registry_factory.go [hunk 2]
```diff
@@ -217,7 +217,35 @@ func (c *compiledGauge) Values(v interface{}) (result []eachValue, errs []error)
...
+					labels := make(map[string]string)
+					ev = &eachValue{
+						Labels: labels,
+						Value:  gotFloat,
+					}
+					didResolveValueFrom = true
+				}
+			}
+			if !didResolveValueFrom {
+				ev, err = c.value(it)
```
Comment (mrueg) [inline pkg/customresourcestate/registry_factory.go:244]: do we need to handle the error here as well?

Comment (rexagod) [reply pkg/customresourcestate/registry_factory.go:244]: The error will get appended [here](https://github.com/kubernetes/kube-state-metrics/pull/1958/files#diff-1cbeb50a6b171ac66f4fad40018421010ed1733ea97fcb40b65a7ebd5e7e3d77R250).

File: pkg/customresourcestate/registry_factory.go (hunk 1 above)
Comment (rexagod) [reply pkg/customresourcestate/registry_factory.go:228]: ACK

File: pkg/customresourcestate/registry_factory.go [hunk 3]
```diff
@@ -143,7 +143,7 @@ type compiledMetric interface {
 	Type() metric.Type
 }
 
-// newCompiledMetric returns a compiledMetric depending given the metric type.
+// newCompiledMetric returns a compiledMetric depending on given the metric type.
```
Comment (mrueg) [inline pkg/customresourcestate/registry_factory.go:146]:
```suggestion
// newCompiledMetric returns a compiledMetric depending on the given metric type.
```

File: pkg/customresourcestate/registry_factory_test.go [hunk 4]
```diff
@@ -173,6 +173,17 @@ func Test_values(t *testing.T) {
 			newEachValue(t, 2, "type", "type-a", "active", "1"),
 			newEachValue(t, 4, "type", "type-b", "active", "3"),
 		}},
+		{name: "path-relative valueFrom value", each: &compiledGauge{
```
Comment (mrueg) [inline pkg/customresourcestate/registry_factory_test.go:176]: Can we add another Test  for this path

```
	if got == nil {
		if c.NilIsZero {
			return &eachValue{
				Labels: labels,
				Value:  0,
			}, nil
		}
```

File: pkg/customresourcestate/registry_factory.go [hunk 5]
```diff
@@ -217,7 +217,40 @@ func (c *compiledGauge) Values(v interface{}) (result []eachValue, errs []error)
...
+			// Try to deduce `valueFrom`'s value from the current element.
+			var ev *eachValue
+			var err error
+			var didResolveValueFrom bool
+			// `valueFrom` will ultimately be rendered into a string and sent to the fallback in place, which also expects a string.
+			// So we'll do the same and operate on the string representation of `valueFrom`'s value.
+			sValueFrom := c.ValueFrom.String()
+			// No comma means we're looking at a unit-length path (in an array).
+			if !strings.Contains(sValueFrom, ",") &&
+				sValueFrom[0] == '[' &&
```
Comment (mrueg) [inline pkg/customresourcestate/registry_factory.go:229]: can we add another check for `sValueFrom[len(sValueFrom)-1] == ']' ?

**Comment by dgrisonnet** [comment]
/assign
/hold

I asked some questions in https://github.com/kubernetes/kube-state-metrics/issues/1947. It is unclear what we are trying to achieve here.

File: pkg/customresourcestate/registry_factory_test.go (hunk 4 above)
Comment (rexagod) [reply pkg/customresourcestate/registry_factory_test.go:176]: This is actually another bug in and of itself. Basically, the same one but for multi-length `valueFrom` paths. In the spirit of keeping the changesets digestible and throughly tested and reviewed in the CRS realm, I thinking if it'd be a better idea to target that in another PR?
***
JFYI the test below returns `nil` for both `main` and this PR.
```go
		{
			name: "multiple path-relative valueFrom values", each: &compiledGauge{
				compiledCommon: compiledCommon{
					path: mustCompilePath(t, "spec"),
					labelFromPath: map[string]valuePath{
						"version": mustCompilePath(t, "version"),
					},
				},
				ValueFrom: mustCompilePath(t, "order", "-1", "id"),
			}, wantResult: []eachValue{
				newEachValue(t, 3, "version", "v0.0.0"),
			},
		},
```

Comment (mrueg) [reply pkg/customresourcestate/registry_factory_test.go:176]: Sounds good to me! Can you add a TODO to the code path?

File: pkg/customresourcestate/registry_factory.go [hunk 6]
```diff
@@ -217,7 +217,41 @@ func (c *compiledGauge) Values(v interface{}) (result []eachValue, errs []error)
...
+			var didResolveValueFrom bool
+			// `valueFrom` will ultimately be rendered into a string and sent to the fallback in place, which also expects a string.
+			// So we'll do the same and operate on the string representation of `valueFrom`'s value.
+			sValueFrom := c.ValueFrom.String()
+			// No comma means we're looking at a unit-length path (in an array).
+			if !strings.Contains(sValueFrom, ",") &&
+				sValueFrom[0] == '[' && sValueFrom[len(sValueFrom)-1] == ']' &&
+				// "[...]" and not "[]".
+				len(sValueFrom) > 2 {
+				extractedValueFrom := sValueFrom[1 : len(sValueFrom)-1]
```
Comment (dgrisonnet) [inline pkg/customresourcestate/registry_factory.go:233]: This is a bit odd to me. ValueFrom is orginally a string array and here we are manually trying to parse it as a string and extracting the first element from it, when we should have an easy access to it. What do you think about adding a new method to `valuePath` that would return a string array instead of a raw string?

Comment (dgrisonnet) [reply pkg/customresourcestate/registry_factory.go:233]: @rexagod I am merging the PR without that change since it is mostly code quality related, but if my suggestion makes sense to you, let's address that in a follow-up
