### PR TITLE
fix: avoid mutating metric families during write

### LINKED ISSUE #2805: Unpredictable format of info metrics
**What happened**:
Hi. Our scraper which collects metric from KSM use such header - Accept: application/openmetrics-text;version=1.0.0;charset=utf-8,application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3
and it receives info metric in such format - # TYPE resource_info info 

but if i make one request to ksm with such headers(like from browser) - Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
it returns metric in such format - # TYPE resource_info gauge

and after this request our scraper receives this metric on all requests as -  # TYPE resource_info gauge

**What you expected to happen**:
I expect that ksm should return metric in same format to all requests with specific headers

**How to reproduce it (as minimally and precisely as possible)**:

```bash
curl -H 'Accept: application/openmetrics-text;version=1.0.0;charset=utf-8,application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3' http://ip-appress-here:8080/metrics | grep 'TYPE resource_info'
# TYPE resource_info info

curl -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' http://ip-appress-here:8080/metrics | grep 'TYPE resource_info'
# TYPE resource_info gauge

# now all requests with specific headers receive gauge, which previously received info
curl -H 'Accept: application/openmetrics-text;version=1.0.0;charset=utf-8,application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3' http://ip-appress-here:8080/metrics | grep 'TYPE resource_info'
# TYPE resource_info gauge
```

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version: 2.17.0
* Kubernetes version (use `kubectl version`): v1.31.8
* Cloud provider or hardware configuration:
* Other info:

### PR DESCRIPTION
**Pull request by bhope**
**What this PR does / why we need it:**

Fixes a bug where metric family types could be mutated across requests when serving different content types.

When serving Prometheus text output, `info` and `stateset` metrics were rewritten to `gauge` by mutating shared metric families. This caused subsequent OpenMetrics requests to return incorrect types. This change ensures per-request sanitization does not affect stored metrics.

**How does this change affect the cardinality of KSM:**  
Does not change cardinality.

**Which issue(s) this PR fixes:**  
Fixes #2805

### CODE REVIEW

**Comment by bhope** [comment]
@mrueg @rexagod this PR is waiting on workflow approval (CI hasn’t started yet). When you have a moment, could you approve the workflow so checks can run? Happy to get a review once CI is green. Thanks!

**Comment by bhope** [comment]
All CI checks have passed now. Thanks.

File: pkg/metrics_store/metrics_store.go
Comment (mrueg) [inline pkg/metrics_store/metrics_store.go]: can you update the comment here to say that it's now a pointer to a map?

File: pkg/metrics_store/metrics_writer.go [hunk 1]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
 				}
 
-				// Nullify duplicate headers after the sanitization to not miss out on any new candidates.
-				if header == lastHeader {
-					writer.stores[0].headers = append(writer.stores[0].headers[:i], writer.stores[0].headers[i+1:]...)
-
-					// Do not increment the index, as the next header is now at the current index.
-					continue
+				if shouldRemove {
+					writer.stores[0].headers[i] = ""
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: Is this better than appending the slice before and after?

Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: @mrueg Good question. I’m intentionally not splicing the slice to keep the header slice length stable, thus avoiding index shifts during iteration. Blanking the entry keeps the slice stable while safely treating the header as a no-op downstream. Happy to adjust if there’s a stronger preference for physical removal, but this felt like the safer tradeoff given how headers are consumed.

File: pkg/metrics_store/metrics_store.go
Comment (bhope) [reply pkg/metrics_store/metrics_store.go]: @mrueg Good catch, updated the comment to reflect that metrics is a pointer to sync.Map. Thanks!

**Comment by bhope** [comment]
Thanks for the review! I’ve addressed the inline comments and updated the PR accordingly. Ready for another look when you have a chance.

**Comment by bhope** [comment]
@mrueg gentle ping in case this got buried - addressed all comments and CI is green. Would appreciate another look when you have time. Thanks!

**Comment by bhope** [comment]
I ran local tests and a small benchmark on the sanitize path. All unit tests pass (including immutability and duplicate handling).

For a worst-case scenario with 100k duplicate headers, `SanitizeHeaders` is ~19ms/op with ~11MB/op and ~200k allocs/op on my machine. I ran `go test ./pkg/metrics_store -bench BenchmarkSanitizeHeaders -benchmem`

The changes in this PR keep the header slice length stable and marks duplicates as "" instead of deleting them. The intention is to preserve index alignment with `metricFamilies[i]` in the non-consecutive duplicate case where deletion risks shifting indices.

File: pkg/metrics_store/metrics_writer.go [hunk 2]
```diff
@@ -59,7 +59,12 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
 
 	for i, help := range m.stores[0].headers {
-		if help != "" && help != "\n" {
+		// Skip empty headers (set by SanitizeHeaders for duplicates)
+		if help == "" {
+			continue
+		}
+
+		if help != "\n" {
 			help += "\n"
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: Could we implement this as part of the SanitizeHeaders func instead, so we do not need to touch the string here again?

File: pkg/metrics_store/metrics_writer.go [hunk 3]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
+					case strings.HasPrefix(line, "# HELP "):
+						fields := strings.Fields(line)
+						if len(fields) >= 3 {
+							metricName := fields[2]
+							if _, seen := seenHELP[metricName]; seen {
+								shouldRemove = true
+								break
+							}
+							seenHELP[metricName] = struct{}{}
+							modifiedLines = append(modifiedLines, line)
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: Move this line out and you can remove the else path

File: pkg/metrics_store/metrics_writer.go [hunk 4]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
-							header = header[:len(header)-len(infoTypeString)] + string(metric.Gauge)
-							writer.stores[0].headers[i] = header
+				lines := strings.Split(header, "\n")
+				shouldRemove := false
+				modifiedLines := make([]string, 0, len(lines))
+
+				for _, line := range lines {
+					switch {
+					case strings.HasPrefix(line, "# HELP "):
+						fields := strings.Fields(line)
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: We can work on the line string directly here, something like this should work to extract the metric name?
```
helpPrefix := "# HELP "
# Get the Index of the second space
spaceIdx := strings.IndexByte(line[len(helpPrefix):], ' ')
if spaceIdx != -1 {
metricName := line[len(helpPrefix):len(helpPrefix) + spaceIdx]
...
}
```

File: pkg/metrics_store/metrics_writer.go [hunk 5]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
 						}
-						if strings.HasSuffix(header, stateSetTypeString) {
-							header = header[:len(header)-len(stateSetTypeString)] + string(metric.Gauge)
-							writer.stores[0].headers[i] = header
+						fields := strings.Fields(line)
+						if len(fields) >= 3 {
+							metricName := fields[2]
+							modifiedLine := line
+							if contentType.FormatType() == expfmt.TypeTextPlain {
+								infoTypeString := string(metric.Info)
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: Should these be moved out and simply be const?

File: pkg/metrics_store/metrics_writer.go (hunk 4 above)
Comment (mrueg) [reply pkg/metrics_store/metrics_writer.go]: Similar applies for the # TYPE below

File: pkg/metrics_store/metrics_writer.go [hunk 6]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
+							break
 						}
-						if strings.HasSuffix(header, stateSetTypeString) {
-							header = header[:len(header)-len(stateSetTypeString)] + string(metric.Gauge)
-							writer.stores[0].headers[i] = header
+						fields := strings.Fields(line)
+						if len(fields) >= 3 {
+							metricName := fields[2]
+							modifiedLine := line
+							if contentType.FormatType() == expfmt.TypeTextPlain {
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: We only modify for TypeTextPlain, can we check that before we even touch anything?

File: pkg/metrics_store/metrics_writer.go [hunk 7]
```diff
@@ -95,49 +100,87 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
+			}
+			// Share the metrics backing storage by sharing the pointer.
+			clonedStore.metrics = store.metrics
+			clonedStores = append(clonedStores, clonedStore)
+		}
+		clonedWriters = append(clonedWriters, &MetricsWriter{stores: clonedStores, ResourceName: writer.ResourceName})
+	}
+
+	// Deduplicate by metric name across all writers to handle non-consecutive duplicates during CRS reload.
+	seenHELP := make(map[string]struct{})
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: Can we preallocate this using len(writer.stores[0].headers)?

File: pkg/metrics_store/metrics_writer.go (hunk 2 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Good call - moved newline handling into SanitizeHeaders. WriteAll now writes headers as-is

File: pkg/metrics_store/metrics_writer.go (hunk 3 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: fixed.

File: pkg/metrics_store/metrics_writer.go (hunk 4 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Agreed, switched to index-based extraction to avoid allocations.

File: pkg/metrics_store/metrics_writer.go (hunk 5 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Yep, moved to file scope.

File: pkg/metrics_store/metrics_writer.go (hunk 6 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Good suggestion, hoisted into a single isTextPlain check.

File: pkg/metrics_store/metrics_writer.go (hunk 7 above)
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Makes sense, added a capacity hint based on total header count.

**Comment by bhope** [comment]
@mrueg Thanks for the thorough review.

Updates in the latest push:
- WriteAll() no longer mutates headers (now a dumb writer)
- newline normalization moved to SanitizeHeaders()
- preallocated HELP/TYPE dedupe maps
- replaced strings.Fields with slice/index parsing
- hoisted TypeTextPlain guard
- moved repeated strings to file scope

Please let me know if you'd like anything adjusted further.

**Comment by bhope** [comment]
Hi @mrueg - wanted to check if you had a chance to review the latest changes. Happy to discuss or make further adjustments. Thanks for your time!

File: pkg/metrics_store/metrics_writer.go
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]:
```suggestion
			_, err = io.WriteString(w, help)
```

Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: Thanks for pointing this out. Fixed now.

**Comment by bhope** [comment]
Hi @mrueg resolved your latest inline comment - ready for another look whenever you have time!

**Comment by bhope** [comment]
`ci-e2e-tests` is currently failing before tests execute due to image tag detection in the e2e script (it was parsing Docker’s human-readable output and treating the image ID as a tag).

I’ve opened a separate fix here: #2875 

This failure is unrelated to the changes in this PR. Once that merges and CI is green. This PR should be merge-ready as-is.

**Comment by bhope** [comment]
@mrueg Thanks for merging #2875 . CI is green now and this PR should be ready. Would appreciate a final look when you have a moment!

**Comment by bhope** [comment]
Rebased and squashed.

File: pkg/metrics_store/metrics_writer.go [hunk 8]
```diff
@@ -59,13 +90,14 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
 	}
 
 	for i, help := range m.stores[0].headers {
-		if help != "" && help != "\n" {
-			help += "\n"
+		// Skip empty headers (set by SanitizeHeaders for duplicates)
+		if help == "" {
+			continue
 		}
```
[the remark this answers is not in the document]
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: addressed - added logic to not skip metric families with empty headers in WriteAll

File: pkg/metrics_store/metrics_writer.go [hunk 9]
```diff
@@ -95,34 +124,94 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
-				// When Prometheus requests proto-based formats, this branch is also used because any requested format that is not OpenMetrics falls back to text/plain in metrics_handler.go.
-				if strings.HasPrefix(header, "# HELP") && contentType.FormatType() == expfmt.TypeTextPlain {
-					infoTypeString := string(metric.Info)
-					stateSetTypeString := string(metric.StateSet)
-					if strings.HasSuffix(header, infoTypeString) {
-						header = header[:len(header)-len(infoTypeString)] + string(metric.Gauge)
-					}
-					if strings.HasSuffix(header, stateSetTypeString) {
-						header = header[:len(header)-len(stateSetTypeString)] + string(metric.Gauge)
+			for i := 0; i < len(writer.stores[0].headers); i++ {
```
Comment (mrueg) [inline pkg/metrics_store/metrics_writer.go]: this looks like we're reverting the change from #2866

Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: You are right, my bad -- will fix the rebase.

Comment (bhope) [reply pkg/metrics_store/metrics_writer.go]: @mrueg -- it took me a bit to wrap my head around this. The actual fix in #2866 was blanking instead of removing headers from the slice. It's back in my PR but we are still blanking, -- so index stability is preserved. So technically this isn't reverting the fix from #2866

File: pkg/metrics_store/metrics_writer.go [hunk 10]
```diff
@@ -59,15 +90,16 @@ func (m MetricsWriter) WriteAll(w io.Writer) error {
...
+			continue
 		}
 
 		var err error
 		m.stores[0].metrics.Range(func(_ interface{}, _ interface{}) bool {
-			_, err = w.Write([]byte(help))
+			_, err = io.WriteString(w, help)
 			if err != nil {
-				err = fmt.Errorf("failed to write help text: %v", err)
+				return false
```
[the remark this answers is not in the document]
Comment (bhope) [reply pkg/metrics_store/metrics_writer.go:94]: fixed

**Comment by bhope** [comment]
Hi @mrueg - The CI is green and Copilot review is addressed too. Ready for your final review.

**Comment by bhope** [comment]
Thanks @mrueg for collaborating with me on this PR. The changes look good! It looks in a good shape.
