### PR TITLE
fix: deduplicate tolerations when generating kube_pod_tolerations

### LINKED ISSUE #2834: Duplicate pod tolerations cause duplicate kube_pod_tolerations metrics and Prometheus ingestion warnings
**What happened**:

Prometheus logs repeated warnings of the form:

```{"caller":"scrape.go:1754","component":"scrape manager","level":"warn","msg":"Error on ingesting samples with different value but same timestamp","num_dropped":308,"scrape_pool":"serviceMonitor/monitoring/prom-op-kube-state-metrics/0","target":"http://11.16.179.111:8080/metrics","ts":"2025-11-17T21:31:37.559Z"}

{"caller":"scrape.go:1754","component":"scrape manager","level":"warn","msg":"Error on ingesting samples with different value but same timestamp","num_dropped":308,"scrape_pool":"serviceMonitor/monitoring/prom-op-kube-state-metrics/0","target":"http://11.16.179.111:8080/metrics","ts":"2025-11-17T21:32:07.545Z"}
```

This occurs on every scrape of kube-state-metrics and results in dropped samples and log flooding.

Investigation shows that kube-state-metrics emits duplicate kube_pod_tolerations samples with identical label sets for certain pods (notably node-local-dns pods in the kube-system namespace).

Example counts from /metrics:

```2 kube_pod_tolerations{namespace="kube-system",pod="node-local-dns-z6rtt",uid="669cc262-dad0-42db-95c4-5d2c1c92b46a",key="CriticalAddonsOnly",operator="Exists"} 1
2 kube_pod_tolerations{namespace="kube-system",pod="node-local-dns-z7prb",uid="dc732c19-ccc6-4581-9991-d53f5bbc43db",key="CriticalAddonsOnly",operator="Exists"} 1
2 kube_pod_tolerations{namespace="kube-system",pod="node-local-dns-z8zn8",uid="ad0ec7aa-0c7c-441f-91e7-d5c7e3437073",key="CriticalAddonsOnly",operator="Exists"} 1
2 kube_pod_tolerations{namespace="kube-system",pod="node-local-dns-zb5ml",uid="def91f6f-78db-4b03-8007-dd306b569c81",key="CriticalAddonsOnly",operator="Exists"} 1
```

These duplicate samples have identical metric name, labels, and timestamp, which Prometheus rejects.

**What you expected to happen**:

kube-state-metrics should emit at most one `kube_pod_tolerations` sample per unique toleration label set per pod, even if the pod spec contains duplicate toleration entries.

Duplicate tolerations are semantically redundant and should not result in duplicate metric samples or Prometheus ingestion warnings.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod with duplicate tolerations:
```apiVersion: v1
kind: Pod
metadata:
  name: dup-tolerations
  namespace: default
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "CriticalAddonsOnly"
    operator: "Exists"
```
2. Deploy kube-state-metrics and scrape its /metrics endpoint.
3. Observe duplicate metric samples:

```kube_pod_tolerations{namespace="default",pod="dup-tolerations",uid="...",key="CriticalAddonsOnly",operator="Exists",value="",effect="",toleration_seconds=""} 1
kube_pod_tolerations{namespace="default",pod="dup-tolerations",uid="...",key="CriticalAddonsOnly",operator="Exists",value="",effect="",toleration_seconds=""} 1
```
4. Prometheus logs warnings and drops samples:

```Error on ingesting samples with different value but same timestamp
```

**Anything else we need to know?**:

- In this environment, the duplication was traced to node-local-dns pods having duplicate tolerations in their PodSpec.
- Example from `kubectl describe pod node-local-dns-<id>`:
```Tolerations:
  :NoSchedule op=Exists
  CriticalAddonsOnly op=Exists
  CriticalAddonsOnly op=Exists
  node-role.kubernetes.io/control-plane:NoSchedule
  node-role.kubernetes.io/master:NoSchedule
  node.kubernetes.io/disk-pressure:NoSchedule op=Exists
  node.kubernetes.io/memory-pressure:NoSchedule op=Exists
  node.kubernetes.io/network-unavailable:NoSchedule op=Exists
  node.kubernetes.io/not-ready:NoExecute op=Exists
  node.kubernetes.io/pid-pressure:NoSchedule op=Exists
  node.kubernetes.io/unreachable:NoExecute op=Exists
  node.kubernetes.io/unschedulable:NoSchedule op=Exists
```
- Duplicate tolerations can be introduced by overlays, mutating admission webhooks, or controllers.
- kube-state-metrics currently emits one metric sample per toleration entry without deduplication.
- Deduplicating tolerations before emitting `kube_pod_tolerations` would prevent invalid duplicate samples and Prometheus log flooding without changing metric semantics.

**Environment**:

- kube-state-metrics version: 2.15.0 (Helm chart kube-state-metrics-5.33.0)
- Kubernetes version (use `kubectl version`): v1.32.7
- Cloud provider or hardware configuration: Azure, GCP and Openstack (Private DCs)
- Other info: Prometheus drops ~308 samples per scrape for kube_pod_tolerations and logs repeated warnings

### PR DESCRIPTION
**Pull request by bhope**
This PR fixes duplicate `kube_pod_tolerations` samples by correcting the deduplication logic in `getUniqueTolerations`.

Previously, `getUniqueTolerations` relied on direct struct comparison of `v1.Toleration`. Since `v1.Toleration` contains pointer fields (notably `*TolerationSeconds`), logically identical tolerations could fail equality comparison and be treated as distinct entries.

As a result, pods containing duplicate tolerations (e.g. repeated `CriticalAddonsOnly` tolerations) could still produce duplicate `kube_pod_tolerations` samples with identical label sets, triggering Prometheus ingestion warnings.

This change updates `getUniqueTolerations` to deduplicate tolerations using a stable identity derived from the toleration’s identity-defining fields (`key`, `operator`, `value`, `effect`, `toleration_seconds`), while preserving existing metric generation behavior.

No changes are made to metric schema or generator logic. This PR strictly corrects the deduplication helper used by the tolerations generator.

Fixes #2834

### CODE REVIEW

**Comment by bhope** [comment]
Thanks for taking a look! This PR addresses duplicate `kube_pod_tolerations` samples emitted when pods contain duplicate toleration entries (observed in production on node-local-dns pods). Duplicate samples cause Prometheus to drop data and log Error on ingesting samples with different value but same timestamp.

The change defensively deduplicates tolerations per pod based on the full exported label set, preserving metric semantics while preventing invalid duplicate samples.

Happy to adjust :)

**Comment by bhope** [comment]
I reverted earlier generator-level changes and limited this PR to fixing getUniqueTolerations.

The generator already relies on this helper, but direct struct comparison of v1.Toleration was insufficient due to pointer fields. Updating the helper to use a stable identity key fixes duplicate metric emission without changing metric schema or generation logic.

**Comment by bhope** [comment]
I’ve added a test to explicitly validate the case where two different `*TolerationSeconds` pointer values contain the same integer. Previously this resulted in duplicate metric emissions because struct comparison treated them as different.

The new test verifies:
• duplicate `key1` tolerations with separate pointer allocations, both with value `3600`, are emitted only once
• a `key1` toleration with different seconds (`1800`) is emitted separately
• for `key2`, both non-nil (`0`) and nil `TolerationSeconds` are correctly treated as distinct identities

This confirms that the updated `getUniqueTolerations` dedupes based on identity-defining values, not pointer equality.

Ready for review 🙌

File: internal/store/pod.go [hunk 1]
```diff
@@ -1685,15 +1685,35 @@ func createPodStatusUnscheduledTimeFamilyGenerator() generator.FamilyGenerator {
 }
 
 // getUniqueTolerations takes an array
```
Comment (mrueg) [inline internal/store/pod.go]:
```suggestion
// getUniqueTolerations takes a v1.Toleration array and returns a deduplicated slice of tolerations based on a stable identity key.
// v1.Toleration contains a pointer field (TolerationSeconds), so we avoid relying on direct struct comparison.
```

**Comment by mrueg** [comment]
thanks for your contribution! 

/lgtm

/hold till end of this week for others to review

**Comment by mrueg** [comment]
/hold cancel

Thanks for your contribution @bhope !
