### PR TITLE
Avoid conflicts when mapping Kubernetes labels to Prometheus labels

### LINKED ISSUE #1115: Unexpected label is not unique error
/kind bug

**What happened**:
We had a pod get created with `ops-managed` and `ops_managed` labels in our cluster. In this scenario, all metrics from kube-state-metrics are getting rejected by Prometheus with label is not unique error message. 

```
level=warn ts=2020-04-06T15:07:36.476Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-service-endpoints target=http://10.4.263.218:8080/metrics msg="append failed" err="label name \"label_ops_managed\" is not unique: invalid sample"
```

**What you expected to happen**:
Metrics to be ingested... with either one or two separate labels in this scenario. 

**How to reproduce it (as minimally and precisely as possible)**:
Add `ops-managed` and `ops_managed` labels to a single pod. 

**Anything else we need to know?**:
I could not find a duplicate issue, my apologies if I overlooked one. Thank you for the help and the great work on this project! 

**Environment:**
v1.9.5 for ksm
v2.16.0 for prometheus

### PR DESCRIPTION
**Pull request by laggyluke**
**What this PR does / why we need it**:

Prometheus 2.16.0 introduced a breaking change that prevents _any_ metrics from being ingested from a target in case _even a single_ metric has duplicate labels.

See https://github.com/prometheus/prometheus/pull/6664

This becomes a problem for ksm as Kubernetes label naming is less restrictive than Prometheus label naming, so we have a "sanitization" process that replaces unsupported characters with an underscore.

A side effect of this process is that it can produce duplicate labels, e.g. Kubernetes labels "foo.bar", "foo-bar" and "foo_bar" are mapped to the same Prometheus label "foo_bar".

Based on the discussion in #1141, we've decided to sort and then automatically rename conflicting labels, so "foo-bar" and "foo_bar" will become "label_foo_bar_conflict1" and "label_foo_bar_conflict2" correspondingly.

If you'd like to have more control over how this conflict is resolved, you should consider addressing this on a different level of the stack, e.g. by standardizing Kubernetes labels using Admission Webhook that ensures that there are no possible conflicts.

**Which issue(s) this PR fixes**:
Fixes #1115

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks @laggyluke ! Let's document this too.

Can we add a note in the README.md as well? It would be good to make users aware of this issue and its resolution .

File: internal/store/utils.go [hunk 1]
```diff
@@ -78,14 +78,44 @@ func kubeLabelsToPrometheusLabels(labels map[string]string) ([]string, []string)
...
+	for key := range labels {
+		sortedKeys = append(sortedKeys, key)
 	}
-	sort.Strings(labelKeys)
+	sort.Strings(sortedKeys)
 
-	labelValues := make([]string, 0, len(labels))
-	for i, k := range labelKeys {
-		labelKeys[i] = prefix + "_" + sanitizeLabelName(k)
+	// conflictDesc holds some metadata for resolving potential lable conflicts
```
Comment (tariq1890) [inline internal/store/utils.go:89]:
```suggestion
	// conflictDesc holds some metadata for resolving potential label conflicts
```

**Comment by laggyluke** [comment]
@tariq1890 Sorry, completely forgot about README.md, here you go.

I've also added a missing ToC reference to "Enabling VerticalPodAustoscalers", hope that's okay.
I wasn't sure about the order between those two (or even where to add it in general), so please let me know if I should move it somewhere.

**Comment by brancz** [comment]
Nice! Looks good to me but giving @lilic and @tariq1890 a chance to review as well.

/hold
/lgtm
/approve

File: README.md [hunk 2]
```diff
@@ -33,6 +33,8 @@ are deleted they are no longer visible on the `/metrics` endpoint.
   - [Resource group version compatibility](#resource-group-version-compatibility)
   - [Container Image](#container-image)
 - [Metrics Documentation](#metrics-documentation)
+  - [Conflict resolution in label names](#conflict-resolution-in-label-names)
+  - [Enabling VerticalPodAustoscalers](#enabling-verticalpodaustoscalers)
```
Comment (tariq1890) [inline README.md:37]: Thank you for this :)

File: README.md [hunk 3]
```diff
@@ -113,10 +115,33 @@ additional metrics!
 
 See the [`docs`](docs) directory for more information on the exposed metrics.
 
+#### Conflict resolution in label names
+
+`*_labels` family of metrics exposes Kubernetes labels as Prometheus labels.
```
Comment (tariq1890) [inline README.md:120]:
```suggestion
The `*_labels` family of metrics exposes Kubernetes labels as Prometheus labels.
```

File: README.md [hunk 4]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+[Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)
```
Comment (tariq1890) [inline README.md:121]:
```suggestion
As [Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)
```

File: README.md [hunk 5]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+is more liberal than
+[Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)
+in terms of allowed characters in label names,
+so we automatically convert unsupported characters to underscores,
```
Comment (tariq1890) [inline README.md:125]:
```suggestion
we automatically convert unsupported characters to underscores.
```

File: README.md [hunk 6]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+e.g. `app.kubernetes.io/name` becomes `label_app_kubernetes_io_name`.
```
Comment (tariq1890) [inline README.md:126]:
```suggestion
For e.g. - `app.kubernetes.io/name` becomes `label_app_kubernetes_io_name`.
```

File: README.md [hunk 7]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+
+This conversion can create conflicts when multiple Kubernetes labels like
+`foo-bar` and `foo_bar` would be converted to the same Prometheus label `label_foo_bar`.
+
+In order to resolve this conflict, a suffix `_conflictN` is automatically added
```
Comment (tariq1890) [inline README.md:131]: We try to avoid passive voice as much as we can.
```suggestion
Kube-state-metrics automatically adds a suffix `_conflictN` to resolve this conflict,
```

File: README.md [hunk 8]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+to all conflicting labels, so the above labels would get converted to
```
Comment (tariq1890) [inline README.md:132]:
```suggestion
so it converts the above labels to
```

File: README.md [hunk 9]
```diff
@@ -113,10 +115,33 @@ additional metrics!
...
+`label_foo_bar_conflict1` and `label_foo_bar_conflict2`.
+
+If you'd like to have more control over how this conflict is resolved,
+you might want to addressing this issue on a different level of the stack,
```
Comment (tariq1890) [inline README.md:136]:
```suggestion
you might want to consider addressing this issue on a different level of the stack,
```

File: README.md (hunk 6 above)
Comment (laggyluke) [reply README.md:126]: This is the only change I'm not sure about as it would basically read "For for example".
Let me change it to simply say "For example".

**Comment by laggyluke** [comment]
@tariq1890 As a non-native English speaker - thank you!
I've fixed the grammar, please let me know if you see anything else to fix.

**Comment by laggyluke** [comment]
Folks, thanks a lot for your support!

**Comment by lilic** [comment]
Thank you!! 🎉 :)

**Comment by mikkeloscar** [comment]
Any plans for when the next release is cut which would include this? :)

**Comment by brancz** [comment]
We're hard at work trying to get an alpha release of [kube-state-metrics 2.0](https://github.com/kubernetes/kube-state-metrics/issues/569) out, it will be included in that. I can't promise when that will be though, as it's vacation season :)

**Comment by lilic** [comment]
@mariusgrigoriu not on the roadmap right now, v2.0 should be out after perf and scale testing, if you want to make that faster testing 2.0 release would be a great help in getting this into newest release! As we have limited resources we try to focus on getting the newest release out.
