### PR TITLE
fix(horizontalpodautoscaler): Added container label to ContainerResource metrics 

### LINKED ISSUE #2403: Duplicate kube_horizontalpodautoscaler_spec_target_metric
**What happened**:

Duplicate `kube_horizontalpodautoscaler_spec_target_metric` causing issues with Prometheus 2.52.0+
Due to new duplicates detection mechanism, I'm seeing following errors in Prometheus:
```
ts=2024-05-28T07:15:26.730Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/kube-prometheus-stack-kube-state-metrics/0 target=http://172.17.60.213:8080/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=12
```

After checking kube-state metrics I've found that metrics for HPA are duplicated:
```
cat metrics | grep 'kube_horizontalpodautoscaler_spec_target_metric{namespace="dummy",horizontalpodautoscaler="dummy",metric_name="cpu",metric_target_type="utilization"}'
kube_horizontalpodautoscaler_spec_target_metric{namespace="dummy",horizontalpodautoscaler="dummy",metric_name="cpu",metric_target_type="utilization"} 100
kube_horizontalpodautoscaler_spec_target_metric{namespace="dummy",horizontalpodautoscaler="dummy",metric_name="cpu",metric_target_type="utilization"} 100
kube_horizontalpodautoscaler_spec_target_metric{namespace="dummy",horizontalpodautoscaler="dummy",metric_name="cpu",metric_target_type="utilization"} 100
```

HPA itself have 3 separate entries for CPU, but there's different on container:
```
k get hpa dummy -oyaml
  metrics:
  - containerResource:
      container: dummy-0
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: ContainerResource
  - containerResource:
      container: dummy-1
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: ContainerResource
  - containerResource:
      container: dummy-2
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: ContainerResource
```

**What you expected to happen**:
kube-state-metrics not producing duplicate metrics, probably by adding container label (?)

**How to reproduce it (as minimally and precisely as possible)**:
- Create HPA as posted above
- Use Prometheus 2.52.0+ as scraper

**Environment**:

* kube-state-metrics version: v2.12.0
* Kubernetes version (use `kubectl version`): v1.28.9-eks-036c24b
* Cloud provider or hardware configuration: EKS

### PR DESCRIPTION
**Pull request by bxrne**
**What this PR does / why we need it:**

Fixes duplicate `kube_horizontalpodautoscaler_spec_target_metric` and `kube_horizontalpodautoscaler_status_target_metric` metrics when multiple containers use the same resource (e.g., CPU) in a HorizontalPodAutoscaler. I also added a unit test case to verify this fix.

*BREAKING CHANGE*: Adding a new label to the stable
kube_horizontalpodautoscaler_status_target_metric

Previously, when an HPA specified multiple ContainerResource metrics with the same resource name but different containers, kube-state-metrics would generate metrics with identical label sets. This caused Prometheus 2.52.0+ to log duplicate metric errors and drop samples:

```
msg="Error on ingesting samples with different value but same timestamp" num_dropped=12
```

This PR adds a `container` label to ContainerResource metrics, making them distinguishable:
- Before: `kube_horizontalpodautoscaler_spec_target_metric{metric_name="cpu",metric_target_type="utilization"}`
- After: `kube_horizontalpodautoscaler_spec_target_metric{metric_name="cpu",metric_target_type="utilization",container="main"}`

For example, an HPA with three containers (main, sidecar1, sidecar2) all scaling on CPU now produces three distinct metrics instead of duplicates.

**How does this change affect the cardinality of KSM:** increases

Cardinality increases slightly for HPAs using ContainerResource metrics. Each container adds one additional metric cardinality dimension. This is the intended behavior to distinguish per-container resource targets.

**Which issue(s) this PR fixes:**

Fixes #2403

### CODE REVIEW

**Comment by bxrne** [comment]
@CatherineF-dev  @mrueg should i mark this PR as stale or backlog, i understand its priority is low?

**Comment by ben-bertrands-hs** [comment]
Hi @bxrne,
Is there a technical reason for closing this pr?

**Comment by bxrne** [comment]
> Hi @bxrne,
> Is there a technical reason for closing this pr?
>  

No. Just hasn't had any activity. 
Happy to reopen.

**Comment by ben-bertrands-hs** [comment]
> Happy to reopen.

That would be awesome. Thanks

File: internal/store/horizontalpodautoscaler.go [hunk 1]
```diff
@@ -50,7 +50,8 @@ var (
 	descHorizontalPodAutoscalerLabelsHelp          = "Kubernetes labels converted to Prometheus labels."
 	descHorizontalPodAutoscalerLabelsDefaultLabels = []string{"namespace", "horizontalpodautoscaler"}
 
-	targetMetricLabels = []string{"metric_name", "metric_target_type"}
+	targetMetricLabels          = []string{"metric_name", "metric_target_type"}
+	containerMetricTargetLabels = []string{"metric_name", "metric_target_type", "container"}
```
Comment (bhope) [inline internal/store/horizontalpodautoscaler.go]: Having a separate label set for `ContainerResource` vs all other types means time series in the same metric family will have inconsistent label schemas --  some with container, some without. This makes it really hard to query across types because the label schemas don't match up.

For non-`ContainerResource` types, lets consider emitting `container=""` instead of omitting the label entirely. That way every metric in the family has the same set of labels.

**Review by bhope — CHANGES_REQUESTED** [review]

File: internal/store/horizontalpodautoscaler.go [hunk 2]
```diff
@@ -194,25 +195,37 @@ func createHPASpecTargetMetric() generator.FamilyGenerator {
...
 				case autoscaling.ResourceMetricSourceType:
 					metricName = string(m.Resource.Name)
 					metricTarget = m.Resource.Target
+					labelKeys = targetMetricLabels
+					labelValues = []string{metricName, ""}
 				case autoscaling.ContainerResourceMetricSourceType:
 					metricName = string(m.ContainerResource.Name)
 					metricTarget = m.ContainerResource.Target
+					labelKeys = containerMetricTargetLabels
+					labelValues = []string{metricName, "", m.ContainerResource.Container}
```
Comment (bhope) [inline internal/store/horizontalpodautoscaler.go]: `kube_horizontalpodautoscaler_status_target_metric` is stable so adding a new label is a breaking change and should be called out as such in the PR description with a changelog. The old behavior was already broken so the fix is needed -- but users will still have to update their dashboards and/or alerts.

File: internal/store/horizontalpodautoscaler.go [hunk 3]
```diff
@@ -253,25 +271,37 @@ func createHPAStatusTargetMetric() generator.FamilyGenerator {
...
 				case autoscaling.ResourceMetricSourceType:
 					metricName = string(m.Resource.Name)
 					currentMetric = m.Resource.Current
+					labelKeys = targetMetricLabels
+					labelValues = []string{metricName, ""}
 				case autoscaling.ContainerResourceMetricSourceType:
 					metricName = string(m.ContainerResource.Name)
 					currentMetric = m.ContainerResource.Current
+					labelKeys = containerMetricTargetLabels
+					labelValues = []string{metricName, "", m.ContainerResource.Container}
```
Comment (bhope) [inline internal/store/horizontalpodautoscaler.go]: Same comment as R223

**Review by bhope — CHANGES_REQUESTED** [review]

**Comment by bhope** [comment]
Thanks for the PR! The fix makes sense and the motivation is solid. Prometheus 2.52+ silently drops these samples -- so users with ContainerResource HPAs are losing this metric entirely. 

I left a few inline comments. We need to be cautious as `kube_horizontalpodautoscaler_status_target_metric` is a stable metric now.

**Comment by bhope** [comment]
Also, please update docs/metrics/workload/horizontalpodautoscaler-metrics.md to reflect container as new label in the existing label list.

**Review by bhope — APPROVED** [review]
