### PR TITLE
Empty string for "owner_*" dimensions in all metrics.

### LINKED ISSUE #1919: Wrong value for empty "owner_" dimensions in 'kube_job_owner' metric
**What happened**:
kube-state-metrics generate below metrics for Kubernetes jobs that doesn't have `metadata.ownerReferences` field (for example, jobs created by Ingress Nginx Controller):
```
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-patch",owner_kind="<none>",owner_name="<none>",owner_is_controller="<none>"} 1
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-create",owner_kind="<none>",owner_name="<none>",owner_is_controller="<none>"} 1
```

**What you expected to happen**:
kube-state-metrics should generate metrics with `""` as a value instead of the current `"<none>"` value:
```
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-patch",owner_kind="",owner_name="",owner_is_controller=""} 1
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-create",owner_kind="",owner_name="",owner_is_controller=""} 1
```

**How to reproduce it (as minimally and precisely as possible)**:
1) Create Kubernetes Job without `metadata.ownerReferences` field
2) Deploy kube-state-metrics
3) Check `kube_job_owner` metrics from kube-state-metrics

**Environment**:
- kube-state-metrics version: 2.7.0
- Kubernetes version (use `kubectl version`): 1.23.12
- Cloud provider or hardware configuration: Openstack with Magnum

### PR DESCRIPTION
**Pull request by pawcykca**
**What this PR does / why we need it**:
Replace "<none>" with empty string for "owner_kind", "owner_name" and "owner_is_controller" dimensions for all metrics.

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
Does not change cardinality.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1919

### CODE REVIEW

File: internal/store/persistentvolumeclaim.go [hunk 1]
```diff
@@ -270,6 +270,6 @@ func getPersistentVolumeClaimClass(claim *v1.PersistentVolumeClaim) string {
 		return *claim.Spec.StorageClassName
 	}
 
-	// Special non-empty string to indicate absence of storage class.
-	return "<none>"
+	// An empty string indicate absence of storage class.
```
Comment (mrueg) [inline internal/store/persistentvolumeclaim.go:273]:
```suggestion
	// An empty string indicates the absence of storage class.
```

**Comment by mrueg** [comment]
I believe easycla is failing because it does not recognize the email in https://github.com/kubernetes/kube-state-metrics/pull/1923/commits/2c3ea01cb2c2ca3fa6ea9958d899f497ef14f5c0.patch ?

**Comment by mrueg** [comment]
/lgtm
/hold
For others to have a look

**Comment by dgrisonnet** [comment]
Thanks @pawcykca!

/lgtm
/unhold
