### PR TITLE
Fix casing while scraping failure reason for `kube_job_status_failed`

### LINKED ISSUE #2045: Scraping the failure reason for a job does a case-sensitive search that fails
**What happened**:
When scraping the failure reason for a job, KSM does a [case-sensitive search](https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L432) for the [keyword `DeadLineExceeded`](https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L42). Since Kubernetes is generating the string `DeadlineExceeded`, the search fails to scrape the reason.

**What you expected to happen**:
A case-insensitive search should be done, so changes in reason's casing would not impact scraping of the metric.

**How to reproduce it (as minimally and precisely as possible)**:
Create a job that fails to meet the `.spec.activeDeadlineSeconds`, forcing Kubernetes to kill the job with reason `DeadlineExceeded`.

**Anything else we need to know?**:
I'm proposing a solution in PR #2046

**Environment**:
- kube-state-metrics version: 2.8.2
- Kubernetes version (use `kubectl version`): 1.26.3

### PR DESCRIPTION
**Pull request by juanjjaramillo**
**What this PR does / why we need it**:
When scraping the failure reason for a job, KSM does a [case-sensitive search](https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L432) for the [keyword `DeadLineExceeded`](https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L42). Since Kubernetes is generating the string `DeadlineExceeded`, the search fails to scrape the reason. This PR proposes to do a case-insensitive search instead, so changes in casing do not affect the scraping of the reason.

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
Does not change cardinality

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2045

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
This metric is a stable metric. https://github.com/kubernetes/kube-state-metrics/blob/main/docs/job-metrics.md

Changing this might break alerts using this reason. 

cc @dgrisonnet do we allow this change for stable metrics?

**Comment by mrueg** [comment]
Was it ever DeadLineExceeded in upstream kubernetes? If not this seems like a bug in kubestatemetrics

**Comment by dgrisonnet** [comment]
Yes this is a bug, I believe it was always `DeadlineExceeded`, but we might have made a typo when introducing the change.

@juanjjaramillo could you perhaps also update the value in https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L42?

**Comment by dgrisonnet** [comment]
@CatherineF-dev yes we do. It is very rare that label value changes are breaking changes and even if they are I think we should always go forward with them, but if there is any doubt, we should always call the change out in the changelog/release note.

Moreover in this particular case it fixes an actual bug that prevent the actual reason to be exposed, so we should definitely fix it.

File: internal/store/job.go [hunk 1]
```diff
@@ -429,5 +430,5 @@ func failureReason(jc *v1batch.JobCondition, reason string) bool {
 	if jc == nil {
 		return false
 	}
-	return jc.Reason == reason
+	return strings.EqualFold(jc.Reason, reason)
```
Comment (dgrisonnet) [inline internal/store/job.go:433]: We want to map the value exactly to make sure that we have a bounded list of potential values, so I don't think we should make that case insensitive. We should rather update the list of reasons and make sure we are more careful in the future to avoid these kind of typos.

Comment (juanjjaramillo) [reply internal/store/job.go]: Makes sense @dgrisonnet 

I have already undo this change. Casing in https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/job.go#L42 was already part of the previous commit, so I only needed to update unit testing to make tests pass. Please let me know if something else is needed.

Thank you for the review!

**Review by dgrisonnet — APPROVED** [review]
Thank you @juanjjaramillo! :)

/lgtm
/approve
