### PR TITLE
fix: set kube_job_status_failed metric even when there are no job.Status.Conditions present

### LINKED ISSUE #2443: Some job metrics are missing if job has no conditions
**What happened**:
Some job metrics (`kube_job_status_failed`, `kube_job_complete`, `kube_job_failed`) are missing for `Job`s without conditions.

**What you expected to happen**:
Metrics are present regardless if conditions exist.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create this job
<details><summary>job.yaml</summary>
<p>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: alpine
        name: test
        command:
          - "sh"
          - "-c"
        args:
          - sleep 5 && exit 1
      restartPolicy: Never
```

</p>
</details>  

2. Observe that the `.status` is missing a `conditions` objects (before the backoffLimit is reached)
3. Observe that e.g., the `kube_job_status_failed` metric is missing (`curl localhost:8080/metrics | grep kube_job_status_failed`)

**Anything else we need to know?**:

The reason for this bug is that the labels and values are only set within a for loop (if a condition of type `Failed` exists):

https://github.com/kubernetes/kube-state-metrics/blob/85d1423b5b896f4fbce8394afed20cfe17371251/internal/store/job.go#L222-L224

I can provide a fix that sets the value regardless if there are any condition with type `Failed`.

**Environment**:

* kube-state-metrics version: `v2.12.0` (master `85d1423`)
* Kubernetes version (use `kubectl version`): `v1.29.6`
* Cloud provider or hardware configuration: homelab

### PR DESCRIPTION
**Pull request by richabanker**
**What this PR does / why we need it**:
Sets the `kube_job_status_failed` metric when a job's conditions are empty. Previously, the metric was only being set while iterating through a job's conditions, thus ignoring the case when no conditions were found but the job still failed.

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*
does not change 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2443

### CODE REVIEW

**Review by dgrisonnet — COMMENTED** [review]
Looks good to me, but could you please add a new test in https://github.com/kubernetes/kube-state-metrics/blob/194a46c09999771736a6e93d8ec48b38219df55e/internal/store/job_test.go to verify that jobs without failed condition have metrics generated?

**Comment by richabanker** [comment]
> Looks good to me, but could you please add a new test in https://github.com/kubernetes/kube-state-metrics/blob/194a46c09999771736a6e93d8ec48b38219df55e/internal/store/job_test.go to verify that jobs without failed condition have metrics generated?

Yep, for sure. Added one, thanks!

**Comment by richabanker** [comment]
Hmm, super weird, when I run `make test-unit` locally - its passing all tests but CI is complaining :/

File: internal/store/job_test.go [hunk 1]
```diff
@@ -214,6 +214,30 @@ func TestJobStore(t *testing.T) {
...
+				},
+				Status: v1batch.JobStatus{
+					Failed: 1,
+				},
+				Spec: v1batch.JobSpec{
+					ActiveDeadlineSeconds: &ActiveDeadlineSeconds900,
+				},
+			},
+			Want: metadata + `
+				kube_job_annotations{job_name="FailedJobWithNoConditions",namespace="ns1"} 1
```
Comment (mrueg) [inline internal/store/job_test.go:233]:
```suggestion

```

File: internal/store/job_test.go [hunk 2]
```diff
@@ -214,6 +214,30 @@ func TestJobStore(t *testing.T) {
...
+				kube_job_owner{job_name="FailedJobWithNoConditions",namespace="ns1",owner_is_controller="",owner_kind="",owner_name=""} 1
+				kube_job_info{job_name="FailedJobWithNoConditions",namespace="ns1"} 1
+				kube_job_labels{job_name="FailedJobWithNoConditions",namespace="ns1"} 1
```
Comment (mrueg) [inline internal/store/job_test.go:236]:
```suggestion

```

If it doesn't have labels and annotations set, these ones should not be created.

File: internal/store/job_test.go (hunk 1 above)
Comment (richabanker) [reply internal/store/job_test.go]: Ahh I just needed to sync to HEAD and it started failing locally too. Thanks fixed now.

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve
