### PR TITLE
Make CRS metrics type dynamic

### LINKED ISSUE #1886: CRS metrics are hardcoded to "gauge" type
**What happened**: CRS metrics are hard-coded to "gauge" as the their TYPE.

**What you expected to happen**: CRS metrics should be able to dynamically deduce the TYPE correctly.

**How to reproduce it (as minimally and precisely as possible)**: PTAL at the example below. 

**Anything else we need to know?**: Surfaced here: https://github.com/kubernetes/kube-state-metrics/pull/1880#discussion_r1016737747.

***
<details>
<summary>Input</summary>

```yaml
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "apps"
        version: "v1"
        kind: "Deployment"
      labelsFromPath:
        name: [metadata, name]
      metrics:
        - name: "test_metrics"
          help: "metrics for debugging"
          each:
            type: Info
            info:
              path: [metadata, annotations]
              labelFromKey: test
```

</details>

<details>
<summary>Output</summary>

```yaml
# HELP kube_crd_test_metrics metrics for debugging
# TYPE kube_crd_test_metrics gauge (<--)
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="deployment.kubernetes.io/revision",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-a",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-b",version="v1"} 2
# HELP kube_crd_test_metrics metrics for debugging
# TYPE kube_crd_test_metrics gauge (<--)
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="deployment.kubernetes.io/revision",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-a",version="v1"} 1
kube_crd_test_metrics{group="apps",kind="Deployment",name="nginx-deployment",test="test-b",version="v1"} 2
```

</details>

***

**Environment**:
- kube-state-metrics version: HEAD

### PR DESCRIPTION
**Pull request by rexagod**
**What this PR does / why we need it**: All CRS metrics are hardcoded to "gauge" type, this patch addresses that.

**How does this change affect the cardinality of KSM**: No change.

**Which issue(s) this PR fixes**: Fixes #1886.

### CODE REVIEW

**Comment by mrueg** [comment]
/lgtm
/hold
for others to review

File: pkg/metric/metric.go [hunk 1]
```diff
@@ -38,12 +38,19 @@ var (
...
 // Type represents the type of a metric e.g. a counter. See
-// https://prometheus.io/docs/concepts/metric_types/.
+// https://prometheus.io/docs/concepts/metric_types/ and,
+// https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metric-types.
 type Type string
 
 // Gauge defines a Prometheus gauge.
 var Gauge Type = "gauge"
 
+// Info defines an OpenMetrics info.
```
Comment (mrueg) [inline pkg/metric/metric.go:48]: Small nit on the comments, do you want to replace "Prometheus" in the counter and gauge comment as well?
